name: photo_manager_example
description: Demonstrates how to use the photo_manager plugin.
version: 3.0.0+26
publish_to: none

environment:
  sdk: ">=2.19.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: # override
  photo_manager_image_provider: # override
#  photo_manager_image_provider: ^2.1.1 # Flutter ^3.14.0

  http: ">=0.13.6 <2.0.0"
  oktoast: ^3.1.0
  path_provider: ^2.0.5
  provider: ^6.0.0
  url_launcher: ^6.1.10
  video_player: ^2.7.2

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  photo_manager:
    path: ../

  path_provider:
    git:
      url: http://gitcode.tongdao.cn/dev28/framework/flutter/thirdparty/ohos_flutter_packages.git
      path: packages/path_provider/path_provider
  video_player:
    git:
      url: http://gitcode.tongdao.cn/dev28/framework/flutter/thirdparty/ohos_flutter_packages.git
      path: packages/video_player/video_player
  url_launcher:
    git:
      url: http://gitcode.tongdao.cn/dev28/framework/flutter/thirdparty/ohos_flutter_packages.git
      path: packages/url_launcher/url_launcher